### ISSUE TITLE
Unexpected token c in JSON at position 0

### ISSUE THREAD

**Issue by TrojanerHD** [TrojanerHD/TrojanerBot#1]
Randomly occurs after some time when starting the bot (in this case it took a few hours/days)

Probably some error handling is required in general
```
FetchError: invalid json response body at https://api.twitch.tv/helix/streams?user_login=<username>&user_login=<other username>&… reason: Unexpected token c in JSON at position 0
    at /home/trojaner/Code/Web/TrojanerBot/node_modules/node-fetch/lib/index.js:272:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  type: 'invalid-json'
}

/home/trojaner/Code/Web/TrojanerBot/node_modules/node-fetch/lib/index.js:272
                                return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
                                                           ^
FetchError: invalid json response body at https://api.twitch.tv/helix/games? reason: Unexpected token c in JSON at position 0
    at /home/trojaner/Code/Web/TrojanerBot/node_modules/node-fetch/lib/index.js:272:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  type: 'invalid-json'
}
```

**Comment by TrojanerHD** [comment]
This is difficult to fix since this error occurs rarely. I will continue to monitor the bug

**Comment by TrojanerHD** [comment]
Also https://github.com/TrojanerHD/TrojanerBot/commit/0f04d3ae04f0f216f3d1b2c72b9d97db3d3e4fd7 was created so the log is more verbose on branch [unstable](https://github.com/TrojanerHD/TrojanerBot/tree/unstable)

**Comment by TrojanerHD** [comment]
Since now, this bug never occurred again. It is considered fixed until it should show up again
