### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by TrojanerHD** [TrojanerHD/TrojanerBot#15]
```
Response: Internal Server Error
    at RequestHandler.execute (/home/trojaner/Code/Web/TrojanerBot/node_modules/discord.js/src/rest/RequestHandler.js:161:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async RequestHandler.push (/home/trojaner/Code/Web/TrojanerBot/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async MessageManager._fetchMany (/home/trojaner/Code/Web/TrojanerBot/node_modules/discord.js/src/managers/MessageManager.js:140:18) {
  code: 500,
  method: 'get',
  path: '/channels/630883093129199656/messages'
}
```
and
```
HTTPError [AbortError]: The user aborted a request.
    at RequestHandler.execute (/home/trojaner/Code/Web/TrojanerBot/node_modules/discord.js/src/rest/RequestHandler.js:93:15)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async RequestHandler.push (/home/trojaner/Code/Web/TrojanerBot/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async MessageManager._fetchMany (/home/trojaner/Code/Web/TrojanerBot/node_modules/discord.js/src/managers/MessageManager.js:140:18) {
  code: 500,
  method: 'get',
  path: '/channels/630883093129199656/messages'
}
```
occur sometimes.
Probably messages that are trying to be fetched and are getting deleted in the process(?)

**Comment by TrojanerHD** [comment]
Since now, this bug never occurred again. It is considered fixed until it should show up again
