### ISSUE TITLE
Bot crashes: channel.isText is not a function

### ISSUE THREAD

**Issue by TrojanerHD** [TrojanerHD/TrojanerBot#79]
```
/home/trojaner/Code/Web/TrojanerBot/node_modules/discord.js/src/client/actions/InteractionCreate.js:48
        if (channel && !channel.isText()) return;
                                ^

TypeError: channel.isText is not a function
    at InteractionCreateAction.handle (/home/trojaner/Code/Web/TrojanerBot/node_modules/discord.js/src/client/actions/InteractionCreate.js:48:33)
    at Object.module.exports [as INTERACTION_CREATE] (/home/trojaner/Code/Web/TrojanerBot/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/trojaner/Code/Web/TrojanerBot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:346:31)
    at WebSocketShard.onPacket (/home/trojaner/Code/Web/TrojanerBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:482:22)
    at WebSocketShard.onMessage (/home/trojaner/Code/Web/TrojanerBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:317:10)
    at callListener (/home/trojaner/Code/Web/TrojanerBot/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/home/trojaner/Code/Web/TrojanerBot/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/home/trojaner/Code/Web/TrojanerBot/node_modules/ws/lib/websocket.js:1180:20)
    at Receiver.emit (node:events:513:28)
```

**Comment by TrojanerHD** [comment]
Update: this seems to be whenever someone tries to update their role. Meaning, trying to change roles will crash the bot. Possible fix: update `discord.js`
